### PR TITLE
MoveInGUI module

### PR DESCRIPTION
**Pull request by x45k**
sometimes there can be a use case to move while in a gui, and odin doesnt have it, so why not add it. it just lets you move while in a gui like your inventory, a terminal, anything.

### CODE REVIEW

**Comment by freebonsai** [comment]
Use the same logic and probably merge this feature together with TermMove module, it does the exact same thing anyway just have an option for everywhere/ only terms. This does not need to be a seperate module.

**Comment by x45k** [comment]
alright makes sense. ill do that when i have time

**Comment by freebonsai** [comment]
Cant you use the method used in TerminalMove.kt considering its 40 lines of code instead of 200?

**Comment by x45k** [comment]
huh? unless im misunderstanding what you mean, what terminal move does is just closes the gui, it doesnt allow movement while inside a gui, hence why it is much longer.

**Pull request closed without merging**
